/**
 * PRODUCTION LATENCY ACCEPTANCE TEST — p95 time-to-first-audio ≤ 2000ms.
 *
 * Part A (HTTP): 20 real conversational turns against the production
 *   streaming turn route — REAL Groq LLM streaming + REAL Fish Audio TTS.
 *   Measures wire-level dispatch→first-audio + the per-stage server block.
 *
 * Part B (BROWSER): 20 turns through the REAL voice pipeline in headless
 *   Chromium with a fake microphone playing real Arabic speech WAVs
 *   (generated by Fish Audio): getUserMedia → VAD endpointing → Whisper
 *   STT → routing → streaming Groq → streaming Fish TTS → playback.
 *   Reads window.__fitnaLatency (always-on instrumentation) — the metric
 *   is speechEnd (acoustic, last VAD voice tick) → firstAudioScheduled.
 *
 * NOTE: headless Chromium cannot run the browser SpeechRecognition
 * service, so Part B exercises the Whisper STT fallback — the SLOWER of
 * the two real client paths. Chrome users on the SpeechRecognition path
 * are strictly faster (no upload+Whisper hop).
 *
 * Run: set -a && source .env && set +a && \
 *      E2E_BASE_URL=https://fitna-ai-production.vercel.app \
 *      npx tsx scripts/latency_acceptance.ts
 */
import { PrismaClient } from "@prisma/client";
import { randomBytes, scrypt as _scrypt, createHmac, createHash } from "node:crypto";
import { promisify } from "node:util";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { chromium } from "playwright";

const scrypt = promisify(_scrypt);
const PARAMS = { N: 16384, r: 8, p: 1, maxmem: 64 * 1024 * 1024 } as const;

const envText = readFileSync(new URL("../.env", import.meta.url), "utf8");
const ENV: Record<string, string> = {};
for (const m of envText.matchAll(/^([A-Z_]+)=(.+)$/gm)) ENV[m[1]] = m[2].trim();

const BASE = process.env.E2E_BASE_URL || "https://fitna-ai-production.vercel.app";
const IS_LOCAL = BASE.includes("localhost") || BASE.includes("127.0.0.1");
// MINI mode: rehearse with the first N turns only (e.g. MINI_TURNS=2).
const MINI = parseInt(process.env.MINI_TURNS || "0", 10) || 0;
const OUT_DIR = "/home/z/my-project/download/latency";
const WAV_DIR = `${OUT_DIR}/utterances`;
mkdirSync(OUT_DIR, { recursive: true });

const db = new PrismaClient();

function authCtxCookie(uid: string, role: string): string {
  const ctx = Buffer.from(JSON.stringify({ uid, role })).toString("base64url");
  const sig = createHmac("sha256", ENV.AUTH_SECRET || "dev").update(ctx).digest("base64url");
  return `fitna_auth_ctx=${ctx}.${sig}`;
}
async function hashPassword(password: string): Promise<string> {
  const salt = randomBytes(16);
  const derived = await scrypt(password.normalize("NFKC"), salt, 64, PARAMS);
  return `scrypt$${PARAMS.N}$${PARAMS.r}$${PARAMS.p}$${salt.toString("base64")}$${derived.toString("base64")}`;
}
function hashToken(raw: string): string {
  const mac = createHmac("sha256", ENV.AUTH_SECRET || "dev").update(raw).digest();
  return createHash("sha256").update(mac).digest("hex");
}

function pct(sorted: number[], p: number): number {
  if (sorted.length === 0) return -1;
  const idx = Math.min(sorted.length - 1, Math.ceil((p / 100) * sorted.length) - 1);
  return sorted[Math.max(0, idx)];
}

type TurnSpec = { wav: string; text: string; session: "sa" | "eg"; expect?: string };

const ALL_TURNS: TurnSpec[] = [
  { wav: "sil_u01_greeting.wav", text: "السلام عليكم ورحمة الله وبركاته", session: "sa" },
  { wav: "sil_u02_howru.wav", text: "كيف حالكم اليوم يا شباب؟", session: "sa" },
  { wav: "sil_u03_call_sultan.wav", text: "يا سلطان، إيه أكبر كسر، اثنين على ستة ولا أربعة على ستة؟", session: "sa", expect: "سلطان" },
  { wav: "sil_u04_call_reem.wav", text: "يا ريم، لو عندنا كسر ثلاثة على ثمانية وواحد على ثمانية، مين أكبر؟", session: "sa", expect: "ريم" },
  { wav: "sil_u05_why.wav", text: "ليه الماء بياخد شكل الكوباية؟", session: "sa" },
  { wav: "sil_u06_praise.wav", text: "برافو عليك يا فهد، إجابة ممتازة!", session: "sa", expect: "فهد" },
  { wav: "sil_u07_attention.wav", text: "مركزين معايا؟ سامعيني كويس؟", session: "sa" },
  { wav: "sil_u08_explain.wav", text: "خلينا نشرح درس النهاردة عن حالات المادة", session: "sa" },
  { wav: "sil_u09_openq.wav", text: "مين فاهم الفرق بين الحالة الصلبة والسائلة؟", session: "eg" },
  { wav: "sil_u10_call_jouri.wav", text: "يا جوري، قوليلنا إيه الفرق بين السائل والغاز؟", session: "sa", expect: "جوري" },
  { wav: "sil_u11_fractions.wav", text: "إيه هو البسط وإيه هو المقام في الكسر؟", session: "sa" },
  { wav: "sil_u12_call_sara.wav", text: "يا سارة، إيه المقصود بالتبخر؟", session: "eg", expect: "سارة" },
  { wav: "sil_u13_call_omar.wav", text: "يا عمر، إزاي بنقارن كسرين ليهم نفس المقام؟", session: "eg", expect: "عمر" },
  { wav: "sil_u14_thanks.wav", text: "شكراً ليكم يا شطار، تعبكم معايا النهاردة", session: "eg" },
  { wav: "sil_u15_watercycle.wav", text: "مين يحكي لي مراحل دورة الماء بالترتيب؟", session: "eg" },
  { wav: "sil_u16_handsup.wav", text: "مين عايز يجاوب؟ ارفع إيدك يا نور", session: "eg", expect: "نور" },
  { wav: "sil_u17_matter.wav", text: "الهواء مادة ولا مش مادة؟ وليه؟", session: "eg" },
  { wav: "sil_u18_call_nour.wav", text: "يا نور، سؤال تاني ليك، إيه اللي بيحصل للمية لما تتسخن؟", session: "eg", expect: "نور" },
  { wav: "sil_u19_encourage.wav", text: "ما تخافش يا ياسين، جرب وقول رأيك", session: "eg", expect: "ياسين" },
  { wav: "sil_u20_farewell.wav", text: "كده خلصنا الدرس، مع السلامة وشكراً على التفاعل", session: "eg" },
];

async function createSession(cookie: string, dialect: "saudi" | "egyptian"): Promise<string> {
  const res = await fetch(`${BASE}/api/sessions/create`, {
    method: "POST",
    headers: { "Content-Type": "application/json", cookie },
    body: JSON.stringify({
      topicId: null,
      durationMinutes: 30,
      classroomStyle: "balanced",
      trainingObjective: "socratic_focus",
      lessonContext: "درس عن الكسور وحالات المادة ودورة الماء",
      teacherTitle: dialect === "saudi" ? "يا أستاذ" : "يا مستر",
      dialect,
    }),
  });
  const json = (await res.json().catch(() => ({}))) as { sessionId?: string; id?: string };
  return json.sessionId || json.id || "";
}

async function main() {
  const TURNS = MINI > 0 ? ALL_TURNS.slice(0, MINI) : ALL_TURNS;
  const report: Record<string, unknown> = {
    base: BASE,
    mode: MINI > 0 ? `mini(${MINI})` : "full",
    startedAt: new Date().toISOString(),
    partA: [] as Record<string, unknown>[],
    partB: [] as Record<string, unknown>[],
  };

  const ts = Date.now();
  const teacher = await db.user.create({
    data: {
      email: `latency-${ts}@fitna.test`,
      fullName: "مدرّس اختبار زمن الاستجابة",
      role: "teacher",
      passwordHash: await hashPassword("TestPass123!"),
    },
  });
  const token = randomBytes(32).toString("base64url");
  await db.authSession.create({
    data: { userId: teacher.id, tokenHash: hashToken(token), expiresAt: new Date(Date.now() + 7200_000) },
  });
  const cookie = `fitna_session=${token}; ${authCtxCookie(teacher.id, "teacher")}`;

  const saSession = await createSession(cookie, "saudi");
  const egSession = await createSession(cookie, "egyptian");
  console.log(`sessions: SA=${saSession.slice(0, 8)} EG=${egSession.slice(0, 8)}`);
  if (!saSession || !egSession) throw new Error("session creation failed");

  // Absorb the serverless cold start exactly like a real room-open does.
  await fetch(`${BASE}/api/sessions/${saSession}/turn/stream`, { method: "GET", headers: { cookie } }).catch(() => {});
  await fetch(`${BASE}/api/sessions/${egSession}/turn/stream`, { method: "GET", headers: { cookie } }).catch(() => {});

  // ==================================================================
  // PART A — HTTP streaming turns (real Groq + real Fish).
  // ==================================================================
  console.log("\n================ PART A: HTTP STREAMING TURNS ================");
  for (let i = 0; i < TURNS.length; i++) {
    const spec = TURNS[i];
    const sessionId = spec.session === "sa" ? saSession : egSession;
    const t0 = Date.now();
    let firstAudioMs = -1;
    let firstByteMs = -1;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const events: any[] = [];
    try {
      const res = await fetch(`${BASE}/api/sessions/${sessionId}/turn/stream`, {
        method: "POST",
        headers: { "Content-Type": "application/json", cookie },
        body: JSON.stringify({
          teacherText: spec.text,
          elapsedMs: 5000 + i * 8000,
          speechDurationMs: 2.5,
        }),
      });
      firstByteMs = Date.now() - t0;
      const reader = res.body!.getReader();
      const decoder = new TextDecoder();
      let buf = "";
      for (;;) {
        const { done, value } = await reader.read();
        if (done) break;
        buf += decoder.decode(value, { stream: true });
        let nl: number;
        while ((nl = buf.indexOf("\n")) >= 0) {
          const line = buf.slice(0, nl).trim();
          buf = buf.slice(nl + 1);
          if (!line) continue;
          try {
            const ev = JSON.parse(line);
            if (ev.type === "audio" && firstAudioMs === -1) firstAudioMs = Date.now() - t0;
            events.push(ev);
          } catch {}
        }
      }
    } catch (err) {
      events.push({ type: "error", error: String(err) });
    }

    const done = events.find((e) => e.type === "done");
    const meta = events.find((e) => e.type === "meta");
    const speech = events.find((e) => e.type === "speech");
    const hadAudio = events.some((e) => e.type === "audio");
    const hadError = events.some((e) => e.type === "error");
    const routingOk = !spec.expect || meta?.routing?.targetName === spec.expect;
    const rec = {
      turn: i + 1,
      text: spec.text.slice(0, 40),
      firstAudioMs,
      firstByteMs,
      server: done?.latency ?? null,
      target: meta?.routing?.targetName ?? null,
      routingOk,
      hadAudio,
      hadError,
      reply: speech?.fullText?.slice(0, 60) ?? null,
      silent: !hadAudio && !hadError && !events.some((e) => e.type === "warn"),
    };
    (report.partA as Record<string, unknown>[]).push(rec);
    console.log(
      `A${String(i + 1).padStart(2, "0")} firstAudio=${String(firstAudioMs).padStart(5)}ms ` +
        `tts0=${done?.latency?.ttsFirstMs ?? "-"} llm1st=${done?.latency?.llmFirstTokenMs ?? "-"} ` +
        `target=${meta?.routing?.targetName ?? "-"}${routingOk ? "" : " (ROUTING MISMATCH)"} ` +
        `audio=${hadAudio} silent=${rec.silent} | ${speech?.fullText?.slice(0, 40) ?? ""}`
    );
    await new Promise((r) => setTimeout(r, 2500));
  }

  // ==================================================================
  // PART B — BROWSER turns through the REAL voice pipeline.
  // ==================================================================
  console.log("\n================ PART B: BROWSER VOICE PIPELINE ================");
  // Fresh sessions: a continuous, realistic lesson per dialect (Part A's
  // history must not pre-seed greetingCompleted for these turns).
  const saSessionB = await createSession(cookie, "saudi");
  const egSessionB = await createSession(cookie, "egyptian");
  await fetch(`${BASE}/api/sessions/${saSessionB}/turn/stream`, { method: "GET", headers: { cookie } }).catch(() => {});
  await fetch(`${BASE}/api/sessions/${egSessionB}/turn/stream`, { method: "GET", headers: { cookie } }).catch(() => {});
  for (let i = 0; i < TURNS.length; i++) {
    const spec = TURNS[i];
    // Local rehearsal: stage the expected transcript for the mock STT.
    if (IS_LOCAL) {
      writeFileSync("/tmp/mock_stt_text.txt", spec.text, "utf8");
    }
    const sessionId = spec.session === "sa" ? saSessionB : egSessionB;
    const wav = `${WAV_DIR}/${spec.wav}`;
    let rec: Record<string, unknown> | null = null;
    let browser;
    try {
      browser = await chromium.launch({
        headless: true,
        args: [
          "--use-fake-device-for-media-stream",
          "--use-fake-ui-for-media-stream",
          `--use-file-for-fake-audio-capture=${wav}`,
          "--autoplay-policy=no-user-gesture-required",
        ],
      });
      const context = await browser.newContext({ locale: "ar-EG" });
      await context.addCookies([
        { name: "fitna_session", value: token, url: BASE },
        { name: "fitna_auth_ctx", value: authCtxCookie(teacher.id, "teacher").split("=")[1], url: BASE },
      ]);
      const page = await context.newPage();
      await page.goto(`${BASE}/session/live/${sessionId}`, { waitUntil: "domcontentloaded", timeout: 45_000 });
      // Open the live mic (the room-mount warmup GET fires automatically).
      const micBtn = page.locator('button:has-text("بدء الحصة")');
      await micBtn.waitFor({ state: "visible", timeout: 20_000 });
      await micBtn.click();

      // Wait for the first latency record (VAD → STT → turn → first audio).
      const deadline = Date.now() + 75_000;
      while (Date.now() < deadline) {
        rec = await page.evaluate(() => {
          const w = window as unknown as { __fitnaLatency?: Record<string, unknown>[] };
          const recs = w.__fitnaLatency ?? [];
          return recs.length > 0 ? recs[0] : null;
        });
        if (rec) break;
        await page.waitForTimeout(1500);
      }
      if (!rec) {
        rec = { turn: i + 1, error: "no latency record (turn never completed)" };
      }
      await browser.close();
    } catch (err) {
      rec = { turn: i + 1, error: String(err).slice(0, 200) };
      await browser?.close().catch(() => {});
    }
    const r = rec as Record<string, unknown>;
    r.turn = i + 1;
    r.text = spec.text.slice(0, 40);
    (report.partB as Record<string, unknown>[]).push(r);
    const ttfa = typeof r.ttfaClientMs === "number" ? r.ttfaClientMs : -1;
    const srv = (r.server ?? {}) as Record<string, unknown>;
    console.log(
      `B${String(i + 1).padStart(2, "0")} TTFA(client)=${String(ttfa).padStart(5)}ms ` +
        `endpointing=${ttfa > 0 && r.transcriptAt && r.speechEndAt ? (r.transcriptAt as number) - (r.speechEndAt as number) : "-"}ms ` +
        `stt+dispatch=${r.transcriptAt && r.dispatchAt ? (r.dispatchAt as number) - (r.transcriptAt as number) : "-"}ms ` +
        `srv(tts0)=${srv.ttsFirstMs ?? "-"} audio=${r.audio} | ${String(r.text ?? "")}`
    );
    await new Promise((r2) => setTimeout(r2, 1500));
  }

  // ==================================================================
  // AGGREGATION + acceptance verdict.
  // ==================================================================
  const aTtfa = (report.partA as Record<string, unknown>[]).map((r) => r.firstAudioMs as number).filter((n) => n > 0).sort((a, b) => a - b);
  const bTtfa = (report.partB as Record<string, unknown>[]).map((r) => r.ttfaClientMs as number).filter((n) => typeof n === "number" && n > 0).sort((a, b) => a - b);
  const silentA = (report.partA as Record<string, unknown>[]).filter((r) => r.silent).length;
  const classroomSilentB = (report.partB as Record<string, unknown>[]).filter((r) => r.classroomSilence === true).length;
  const silentB = (report.partB as Record<string, unknown>[]).filter((r) => !r.audio && !r.error && r.classroomSilence !== true).length;
  const routingFails = (report.partA as Record<string, unknown>[]).filter((r) => r.routingOk === false).length;

  report.summary = {
    partA: { n: aTtfa.length, p50: pct(aTtfa, 50), p90: pct(aTtfa, 90), p95: pct(aTtfa, 95), max: aTtfa[aTtfa.length - 1] ?? -1, silentTurns: silentA },
    partB: { n: bTtfa.length, p50: pct(bTtfa, 50), p90: pct(bTtfa, 90), p95: pct(bTtfa, 95), max: bTtfa[bTtfa.length - 1] ?? -1, silentTurns: silentB, classroomSilenceTurns: classroomSilentB },
    routingFails,
    acceptance: {
      criterion: "p95 time-to-first-audio (browser, real voice pipeline) ≤ 2000ms, no silent turns",
      browserP95: pct(bTtfa, 95),
      passed: pct(bTtfa, 95) <= 2000 && silentA === 0 && silentB === 0 && routingFails === 0 && bTtfa.length === TURNS.length,
    },
  };

  writeFileSync(`${OUT_DIR}/latency_report.json`, JSON.stringify(report, null, 2));
  console.log("\n================ SUMMARY ================");
  console.log(`Part A (HTTP stream): n=${aTtfa.length} p50=${pct(aTtfa, 50)}ms p95=${pct(aTtfa, 95)}ms silent=${silentA}`);
  console.log(`Part B (browser voice): n=${bTtfa.length} p50=${pct(bTtfa, 50)}ms p95=${pct(bTtfa, 95)}ms silent=${silentB}`);
  console.log(`Routing mismatches: ${routingFails}`);
  console.log(`ACCEPTANCE: ${(report.summary as Record<string, Record<string, unknown>>).acceptance.passed ? "PASS ✅" : "FAIL ❌"}`);
  console.log(`report: ${OUT_DIR}/latency_report.json`);

  await db.$disconnect().catch(() => {});
  process.exit(0);
}

main().catch(async (err) => {
  console.error("FATAL:", err);
  await db.$disconnect().catch(() => {});
  process.exit(1);
});
